### ISSUE TITLE
Handling of isolated vertices

### ISSUE THREAD

**Issue by anmiri** [kramsretlow/Autologistic.jl#13]
Hi,
I am just wondering, from a theoretical perspective, how the ALRsimple model deals with isolated vertices. Say you have a neighbourhood matrix with a lot of isolated vertices - how would this affect the spatial association parameter? Are isolated vertices ignored or do they contribute to the association estimate?

**Comment by kramsretlow** [comment]
First, really sorry for not responding to this question! The notification got buried in my email and I wasn't aware of it until yesterday.

This is a good question.  In the case where you have a graph with isolated vertices, or several disjoint parts, everything should still work as expected.  The isolated vertices aren't explicitly ignored, but they will not play any role in the estimation of the association parameter, because those vertices only contribute zeros to the pseudolikelihood.  As long as you have some edges in the graph, you should get a reasonable estimate for the association parameter, but the standard error of your estimate might be high--reflecting limited information about the association--if the number of edges is small.

The isolated vertices will still contribute to the estimation of the regression parameters, of course.

In the case of a totally disconnected graph (with zero edges), the association parameter will not be identifiable.  This case is just standard logistic regression, so one should probably use a package like `GLM` instead.
